title: Krishna's ESIIL training portfolio
description: Researcher in meteorology specializing in dust aerosols
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-remote-theme
collections:
  - sections
email: krishnaap7@gmail.com
baseurl: "/esiil_course"       # project-site path
url: "https://krishnaap.github.io"
