remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-remote-theme
collections:
  - sections
include:
  - assets/css/custom.css  

title: "Krishnakumar's Portfolio"
subtitle: "Researcher in Meteorology"
description: "Dust aerosol specialist impacting weather & climate"
avatar: https://avatars.githubusercontent.com/u/10349239?v=4
baseurl: "/esiil_course"
url: "https://krishnaap.github.io"
email: krishnaap7@gmail.com
socials:
  - name: GitHub
    url: https://github.com/krishnaap
    icon: fa-github
  - name: Google Scholar
    url:  https://scholar.google.com/citations?user=8RzH7mcAAAAJ&hl=en
    icon: fa-graduation-cap
    icon-style: solid

